Schnittcher/IPS-Zigbee2MQTT

Device/locale.json
libs/Zigbee2MQTTHelper.php

except action_color (XY) work in progress

Add Illuminize RC_Action

---

.styles
Device/locale.json
libs/Zigbee2MQTTHelper.php

Add backlight_mode, change calibration_time from Integer to Float

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Several adds and corrections

---

Configurator/locale.json
Device/locale.json
libs/Zigbee2MQTTHelper.php

Calibration, motor_reversal, backlight did'nt run. Cannot autoconvert Error fixed. Add Dual Shutter Module.

Correction for Shutter and add Temperature L1-L4 for custom devices

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Add some correction to vobration and Aqara cube

Add some correction to vobration and Aqara cube

---

libs/Zigbee2MQTTHelper.php

added case 'Z2M.effect.dd503500':

Expose 'effect' expand with new effects specially for HUE 

---

libs/Zigbee2MQTTHelper.php

Z2M.keypad_lockout.84f3d9b9
Z2M.programming_operation_mode.5dfa482f
Z2M.setpoint_change_source.2b697f02
Z2M.day_of_week.87770221
Z2M.adaptation_run_status.cc98878f
Z2M.adaptation_run_control.e596b9f2

Fixed enum-profiles

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Aqara SP-EUC01 EU smart plug https://www.zigbee2mqtt.io/devices/SP-EUC01.html#xiaomi-sp-euc01
button_lock
TuYa Plant Soil sensor https://www.zigbee2mqtt.io/devices/TS0601_soil.html#tuya-ts0601_soil
soil_moisture, temperature_unit, battery_state

Add new exposes

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Both Exposes for the Bosch TRV

ADD: Z2M_RemoteTemperature & Z2M_DisplayedTemperature

---

libs/Zigbee2MQTTHelper.php

Profile for Zigbee/RF curtain converter:
https://www.zigbee2mqtt.io/devices/ZM-AM02_cover.html#zemismart-zm-am02_cover

Add: Z2M.motor_direction.cf88002f

---

libs/Zigbee2MQTTHelper.php

Fixed:
Z2M_HeartbeatIndicator & Z2M_LinkageAlarm

Fix: Xiaomi JY-GZ-01AQ Smokedetector

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Fix: Z2M.action.869d1272 & Z2M.action.ec8cf04f

---

libs/Zigbee2MQTTHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/2449?u=burki24

ADD: Z2M.mode.c348e40f

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/2530?u=burki24

ADD: Z2M_TRVError

---

libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/2554?u=burki24

Fix: action_transaction (Z2M.action_transaction)

---

libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/2606?u=burki24

ADD: enum - Z2M.action.177702c6

---

libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/2609?u=burki24

ADD: numeric - Z2M_MotionSensitivity

---

libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/2635?u=burki24

ADD: Enum - Z2M.action.be89cdac

---

Bridge/module.php

Small extension to intercept the announce event of devices. Adds the variable 'Announce' with ident 'Z2M_Device_Announce'!

Add event:device_announce

---

libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/2707?u=burki24

ADD: Z2M.effect.5b9efbea

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/2706

ADD: Z2M_TransmitPower

---

libs/Zigbee2MQTTHelper.php

Attenteion: This change builds a new Variable, if the device is already registered in Symcon.

FIX: Z2M_Pi_Heating_Demand -> Z2M_PiHeatingDemand

---

libs/IPSymconExtension.js

FIX: IPSymconExtension.js - vendor, description, model.

---

libs/Zigbee2MQTTHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/2973?u=burki24
https://community.symcon.de/t/modul-zigbee2mqtt/49507/2996?u=burki24

ADD: new Profiles

---

libs/ColorHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/3107?u=burki24

FIX: calculating HS

---

actions/setWithTransition.json

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/3459?u=burki24

FIX: setWithTransition.json

---

libs/Zigbee2MQTTHelper.php

Wrong translation in state_rgb & state_cct (line 1996, 2000)

FIX: Zigbee2MQTTHelper.php

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/3518

FIX: multiple fixes

---

Device/form.json

Add TestCenter for devices

---

libs/Zigbee2MQTTHelper.php

@Nall-chan Danke für den Hinweis.

FIX: action_rate, action_level, action_transition_time

---

Bridge/form.json
Bridge/locale.json
Bridge/module.php

Prüft ob permit_join in der configuration.yaml aktiv ist.

---

.github/workflows/style.yml
.github/workflows/tests.yml
.gitmodules
Bridge/form.json
Bridge/locale.json
Bridge/module.json
Bridge/module.php
Configurator/form.json
Configurator/locale.json
Configurator/module.json
Configurator/module.php
Device/form.json
Device/locale.json
Device/module.json
Device/module.php
Group/form.json
Group/locale.json
Group/module.json
Group/module.php
README.md
Todo
library.json
libs/ColorHelper.php
libs/IPSymconExtension.js
libs/MQTTHelper.php
libs/Zigbee2MQTTHelper.php
tests/LibraryTest.php
tests/phpunit.xml

Konfigurator, Extension und Kommunikation mit der Extension überarbeitet.
Alle PRs von @Burki24 sind ebenfalls enthalten.

Testing version

---

libs/Zigbee2MQTTHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/3621?u=burki24

FIX: Z2M_Schedule & Z2M_ScheduleSettings & Z2M_CycleIrrigationInterval

---

Device/locale.json
libs/Zigbee2MQTTHelper.php

Belongs to: https://community.symcon.de/t/modul-zigbee2mqtt/49507/3796?u=burki24

ADD: Bosch-Thermostat BTH-RM fehlende Exposes

---

libs/Zigbee2MQTTHelper.php

belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/3811?u=burki24

ADD: Z2M.mode.cc8717a5

---

libs/Zigbee2MQTTHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/3819?u=burki24

FIX: occupied_cooling_setpoint

---

libs/Zigbee2MQTTHelper.php

Belongs to:
https://community.symcon.de/t/modul-zigbee2mqtt/49507/3820?u=burki24

ADD: Z2M.action.c09aa43b & Z2M.action.83170026

---

Bridge/form.json
Bridge/locale.json
Bridge/module.php
README.md
library.json
libs/ColorHelper.php
libs/IPSymconExtension.js
libs/MQTTHelper.php
libs/Zigbee2MQTTHelper.php

Bridge Instanz aktualisiert die Extension zur Vorbereitung auf das kommende Modul Update

Vorbereitung für Modul Update 5.0
